Awesome books
amanuelbelete95/awesome-books pull request #1
Opened 2023-02-13 16:35 UTC by gaks1

1. Created simple HTML to add and remove books.
2. Create javascript to add, remove and store books locally.
3. Created simple css for the hr element.
4. Added linters.

2023-02-13 16:57 UTC, laiifuu reviewed
# Status: Invalidated :stop_sign: 

## Hi team :wave:  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- You have submitted a project that doesn't have a descriptive README. You used the template provided by Microverse, however, you need to fill it with your own information.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-13 16:59 UTC, gaks1 commented
@laiifuu  Hello but we have descriptive readme  that has our information on this branch

2023-02-13 17:09 UTC, laiifuu commented
@gaks1, I appologize I made a mistake. I'm terribly sorry. In that case you can go ahead and re submit for another review. Since it was an invalidation, your number of reviews should be intact. Again, I'm very sorry about this.

2023-02-13 18:16 UTC, NahnahAJ requested changes
Hi @gaks1 and @amanuelbelete95 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media2.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights
- [ ] No linter errors :heavy_check_mark: 
- [ ] Good use of GitHub flow :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-13 18:16 UTC, nahnahdev commented on README.md
>    <summary>Client</summary>
- [ ] Kindly replace this section with the right information. This is how it currently looks
- 
![image](https://user-images.githubusercontent.com/102699958/218527110-6247693e-9d47-449a-9241-5b060507e4fc.png)

2023-02-13 18:16 UTC, NahnahAJ commented on script.js
> +}
- [ ] It looks like there is a problem with your function to add a book. As a result of this, I am unable to add books
 to your app . I have attached a video below for your reference :100: 
[Screencast from 02-13-2023 05:52:22 PM.webm](https://user-images.githubusercontent.com/102699958/218536308-98fdc187-fdcb-42d0-ad8a-264924284615.webm)
- [ ] It throws this error in the console

2023-02-14 09:32 UTC, ABDULALI3468 requested changes
# Changes Required 👍 

Hi @amanuelbelete95 , 

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

Great work on making the changes requested by a previous reviewer 👏 
You've done really well implementing some of the requested changes, but there are still some which aren't been addressed yet.


## Highlights 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.


 ## Required Changes ♻️

> **_Check the comments below to have a look at the required changes._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-14 09:32 UTC, ABDULALI3468 commented on script.js
> +}
As requested by the Previous Code Reviewer the problem still exists with your function and user are not able to add a book.  

After seeing it a bit I found that the problem is with the `bookArrayString1` it is not presented when the page loads. Consider adding it as an empty array to the local storage when the page loads and then add the further objects in it. There may be some other reasons and problems with the function so consider rechecking it as they still exist.

2023-02-14 12:23 UTC, AnselemOdims approved these changes
### Hi  @amanuelbelete95 🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-14 12:24 UTC, merged